title: "Professor of Economics and Political Science"
url: "https://duttp.github.io/"    # full URL, no trailing slash

remote_theme: le4ker/personal-jekyll-theme@v9.0.0

plugins:
  - jekyll-remote-theme
